### ISSUE TITLE
Dimension mismatch for LayerNorm when add_feed_forward is set to True

### ISSUE THREAD

**Issue by vicdare** [lucidrains/make-a-video-pytorch#12]
Hi, thanks for your great work! I tried running the test script provided for SpatioTemporalAttention but got this error "RuntimeError: The size of tensor a (16) must match the size of tensor b (682) at non-singleton dimension 4". How do I fix this?

Thanks

**Comment by lucidrains** [comment]
@vicdare oops! should be fixed in 0.2.0!
